"""initial schema

Revision ID: 82af8fb99f56
Revises: 
Create Date: 2026-05-08 22:52:17.231396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82af8fb99f56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('semester', sa.Text(), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('exam_format', sa.Text(), nullable=True),
    sa.Column('professor', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concepts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('course_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('target_bloom', sa.Integer(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('source_pages', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('course_id', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('indexed', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_exams',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('course_id', sa.Text(), nullable=True),
    sa.Column('based_on', sa.Text(), nullable=True),
    sa.Column('started_at', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.Text(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_sessions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('course_id', sa.Text(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('course_id', sa.Text(), nullable=True),
    sa.Column('concept_id', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('front', sa.Text(), nullable=True),
    sa.Column('back', sa.Text(), nullable=True),
    sa.Column('bloom_level', sa.Integer(), nullable=True),
    sa.Column('fsrs_state', sa.JSON(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('lapse_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coaching_sessions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('course_id', sa.Text(), nullable=True),
    sa.Column('concept_id', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('diagnostic', sa.JSON(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concept_edges',
    sa.Column('src', sa.Text(), nullable=False),
    sa.Column('dst', sa.Text(), nullable=False),
    sa.Column('relation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['dst'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['src'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('src', 'dst', 'relation')
    )
    op.create_table('material_chunks',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('material_id', sa.Text(), nullable=True),
    sa.Column('course_id', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_questions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('course_id', sa.Text(), nullable=True),
    sa.Column('concept_id', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('bloom_level', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('grounding', sa.JSON(), nullable=True),
    sa.Column('user_flagged', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worked_examples',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('course_id', sa.Text(), nullable=True),
    sa.Column('concept_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('user_stage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('question_id', sa.Text(), nullable=True),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('card_id', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('elapsed_days', sa.Float(), nullable=True),
    sa.Column('state_before', sa.JSON(), nullable=True),
    sa.Column('state_after', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('quiz_attempts')
    op.drop_table('worked_examples')
    op.drop_table('quiz_questions')
    op.drop_table('material_chunks')
    op.drop_table('concept_edges')
    op.drop_table('coaching_sessions')
    op.drop_table('cards')
    op.drop_table('plan_sessions')
    op.drop_table('mock_exams')
    op.drop_table('materials')
    op.drop_table('concepts')
    op.drop_table('courses')
    # ### end Alembic commands ###
