"""coaching_session_started_at_datetime_duration_float

Revision ID: 85dd8e6f264e
Revises: af41f839d78e
Create Date: 2026-05-09 13:34:33.977951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85dd8e6f264e'
down_revision: Union[str, Sequence[str], None] = 'af41f839d78e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaching_sessions', schema=None) as batch_op:
        batch_op.alter_column('duration_min',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('started_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_index('ix_coaching_sessions_concept_id', ['concept_id'], unique=False)
        batch_op.create_index('ix_coaching_sessions_course_id', ['course_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaching_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_coaching_sessions_course_id')
        batch_op.drop_index('ix_coaching_sessions_concept_id')
        batch_op.alter_column('started_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('duration_min',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
