"""cards_reviews_datetime_and_indexes

Revision ID: af41f839d78e
Revises: ee7ebfd3fa06
Create Date: 2026-05-09 12:40:02.695660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af41f839d78e'
down_revision: Union[str, Sequence[str], None] = 'ee7ebfd3fa06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_index('ix_cards_course_archived', ['course_id', 'archived'], unique=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('reviewed_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_index('ix_reviews_card_id', ['card_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_reviews_card_id')
        batch_op.alter_column('reviewed_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index('ix_cards_course_archived')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
