"""materials_uploaded_at_datetime

Revision ID: ee7ebfd3fa06
Revises: 82af8fb99f56
Create Date: 2026-05-09 11:06:19.635444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7ebfd3fa06'
down_revision: Union[str, Sequence[str], None] = '82af8fb99f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.alter_column('uploaded_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.alter_column('uploaded_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
